apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: jagadirsimpleapi 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jagadirsimpleapi 
    spec:
      containers:
        - name: jagadirsimpleapi 
          image: claimproc001.azurecr.io/jagadirsimpleapi
          ports:
          - containerPort: 80