apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi-deployment
spec:
  selector:
    matchLabels:
      app: simpleapi
  template:
    metadata:
      labels:
        app: simpleapi
    spec:
      containers:
      - name: simpleapi
        image: claimproc001.azurecr.io/simpleapi:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
